spring:
  datasource:
    url: jdbc:mariadb://db:3306/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

rootDirectory: /home/cnb/app/
officialDocDirectory: ${rootDirectory}oficios/
userProfileImgDirectory: ${rootDirectory}fotosPerfil/


