spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/semcitecSystemDB
    username: semcitecUser
    password: semcitecPassword

rootDirectory: ${USERPROFILE}/app/
officialDocDirectory: ${rootDirectory}oficios/
userProfileImgDirectory: ${rootDirectory}fotosPerfil/
