spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local} # perfil default local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

